/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import modelo.FlujoCaja;
import modelo.Caja;
import dao.FlujoCajaDAO;
import dao.CajaDAO;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesé
 */
public class CajaForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form CajaForm
     */
    FlujoCaja fc = new FlujoCaja();
    FlujoCajaDAO fcdao = new FlujoCajaDAO();
    Caja ca = new Caja();
    CajaDAO caDAO = new CajaDAO();
    int nCaja;
    int idCaja = caDAO.listarId(nCaja);

    ImageIcon icon = new ImageIcon("");

    public CajaForm() {
        initComponents();
        this.setFrameIcon(icon);
        nCaja = Integer.parseInt(Login.nCaja);
        cajaAbierta();
        efectivo();
    }

    void cajaAbierta() {
        int idCaja = caDAO.listarId(Integer.parseInt(Login.nCaja));

        fc.setIdCaja(idCaja);
        fc.setIdVendedor(Login.idVendedor);
        fc.setFecha(fecha());

        if (fcdao.cajaAbierta(fc)) {
            btnAbrir.setEnabled(false);
            txtInicial.setEnabled(false);
            jLabel1.setEnabled(false);

            btnCerrar.setEnabled(true);
            btnDepositar.setEnabled(true);
            btnRetirar.setEnabled(true);
            txtRetirar.setEnabled(true);
        } else {
            btnCerrar.setEnabled(false);
            btnDepositar.setEnabled(false);
            btnRetirar.setEnabled(false);
            txtRetirar.setEnabled(false);

            btnAbrir.setEnabled(true);
            txtInicial.setEnabled(true);
            jLabel1.setEnabled(true);
        }
    }

    boolean esNumerico(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    double montoRetiro;
    double efectivo;

    void retirarEfectivo() {
        efectivo = Double.parseDouble(txtEfectivo.getText());

        if (esNumerico(txtRetirar.getText())) {
            if (Double.parseDouble(txtRetirar.getText()) > efectivo) {
                JOptionPane.showMessageDialog(this, "Monto a retirar insuficiente");
            } else {
                montoRetiro = Double.parseDouble(txtRetirar.getText());
                int idCaja = caDAO.listarId(Integer.parseInt(Login.nCaja));
                fc.setIdCaja(idCaja);
                fc.setIdVendedor(Login.idVendedor);
                fc.setFecha(fecha());
                FlujoCaja f = fcdao.efectivo(fc);
                double total = f.getTotal() - montoRetiro;
                double egreso = f.getEgreso() + montoRetiro;

                FlujoCaja retiro = new FlujoCaja();
                retiro.setIdCaja(idCaja);
                retiro.setIdVendedor(Login.idVendedor);
                retiro.setFecha(fecha());
                retiro.setEgreso(egreso);
                retiro.setTotal(total);
                fcdao.retirarEfectivo(retiro);
                
                List<FlujoCaja> flujo = fcdao.datosCajaAbierta(fc);
                int idFlujo = flujo.get(0).getIdFLujoCaja();
                 
                fcdao.detalleRetirarEfetivo(idFlujo, 0, montoRetiro, "Retiro");
                JOptionPane.showMessageDialog(this, "Efectivo retirado");
                efectivo();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un monto numerico");
        }
    }

    void abrirCaja() {
        fc.setIdCaja(idCaja);
        fc.setIdVendedor(Login.idVendedor);
        fc.setFecha("" + fecha());

        if (fcdao.cajaAbierta(fc)) {
        } else {
            fcdao.abrirCaja(fc);
        }
    }

    String fecha() {
        Calendar calendar = new GregorianCalendar();
        int anno = calendar.get(Calendar.YEAR);
        int mes = calendar.get(calendar.MONTH) + 1;
        int dia = calendar.get(Calendar.DAY_OF_MONTH);

        return (anno + "-" + mes + "-" + dia);
    }

    void efectivo() {
        fc.setIdCaja(idCaja);
        fc.setIdVendedor(Login.idVendedor);
        fc.setFecha("" + fecha());
        FlujoCaja efe = fcdao.efectivo(fc);
        txtEfectivo.setText("" + efe.getTotal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbrir = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        txtInicial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtRetirar = new javax.swing.JTextField();
        btnRetirar = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JTextField();

        setClosable(true);
        setForeground(java.awt.Color.gray);
        setTitle("Caja");

        btnAbrir.setText("Abrir Caja");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        jLabel1.setText("Monto Inicial:");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingreso", "Egreso", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnDepositar.setText("Depositar");

        btnCerrar.setText("Cerrar Caja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetirar)
                    .addComponent(btnCerrar)
                    .addComponent(btnDepositar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Efectivo:");

        txtEfectivo.setEditable(false);
        txtEfectivo.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEfectivo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(jLabel1)
                    .addComponent(txtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        abrirCaja();
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        retirarEfectivo();
    }//GEN-LAST:event_btnRetirarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAbrir;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtInicial;
    private javax.swing.JTextField txtRetirar;
    // End of variables declaration//GEN-END:variables
}
