/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dao.CajaDAO;
import dao.FlujoCajaDAO;
import modelo.FlujoCaja;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JInternalFrame;
import modelo.Caja;

/**
 *
 * @author Jesé
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    FlujoCaja fc = new FlujoCaja();
    FlujoCajaDAO fcdao = new FlujoCajaDAO();
    Caja ca = new Caja();
    CajaDAO caDAO = new CajaDAO();

    public Principal() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/cart.png")));
        this.setExtendedState(MAXIMIZED_BOTH);
        privilegio(Login.tipo);
        cajaAbierta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGenerarVenta = new javax.swing.JMenuItem();
        menuCaja = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCategoria = new javax.swing.JMenuItem();
        menuProducto = new javax.swing.JMenuItem();
        menuVendedor = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenuItem();
        menuProveedor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuRanking = new javax.swing.JMenuItem();
        menuIngresos = new javax.swing.JMenuItem();
        menuEgresos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuActualizar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuGenerarCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");

        javax.swing.GroupLayout ventanaPrincipalLayout = new javax.swing.GroupLayout(ventanaPrincipal);
        ventanaPrincipal.setLayout(ventanaPrincipalLayout);
        ventanaPrincipalLayout.setHorizontalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        ventanaPrincipalLayout.setVerticalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        menu.setText("Menu");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menu.add(menuSalir);

        menuCerrar.setText("Cerrar Sesión");
        menuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarActionPerformed(evt);
            }
        });
        menu.add(menuCerrar);

        jMenuBar1.add(menu);

        jMenu2.setText("Ventas");

        menuGenerarVenta.setText("Generar Venta");
        menuGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerarVentaActionPerformed(evt);
            }
        });
        jMenu2.add(menuGenerarVenta);

        menuCaja.setText("Caja");
        menuCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCajaActionPerformed(evt);
            }
        });
        jMenu2.add(menuCaja);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mantenimiento");

        menuCategoria.setText("Categoria");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(menuCategoria);

        menuProducto.setText("Producto");
        menuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductoActionPerformed(evt);
            }
        });
        jMenu3.add(menuProducto);

        menuVendedor.setText("Vendedor");
        menuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendedorActionPerformed(evt);
            }
        });
        jMenu3.add(menuVendedor);

        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu3.add(menuCliente);

        menuProveedor.setText("Proveedor");
        menuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProveedorActionPerformed(evt);
            }
        });
        jMenu3.add(menuProveedor);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");

        menuRanking.setText("Ranking Ventas");
        menuRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRankingActionPerformed(evt);
            }
        });
        jMenu4.add(menuRanking);

        menuIngresos.setText("Ingresos");
        menuIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresosActionPerformed(evt);
            }
        });
        jMenu4.add(menuIngresos);

        menuEgresos.setText("Egresos");
        menuEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEgresosActionPerformed(evt);
            }
        });
        jMenu4.add(menuEgresos);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Administrador");

        menuActualizar.setText("Actualizar Admin");
        menuActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizarActionPerformed(evt);
            }
        });
        jMenu1.add(menuActualizar);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Compras");

        menuGenerarCompra.setText("Generar Compra");
        menuGenerarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerarCompraActionPerformed(evt);
            }
        });
        jMenu5.add(menuGenerarCompra);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void cajaAbierta() {
        int idCaja = caDAO.listarId(Integer.parseInt(Login.nCaja));

        Calendar calendar = new GregorianCalendar();
        int anno = calendar.get(Calendar.YEAR);
        int mes = calendar.get(calendar.MONTH) + 1;
        int dia = calendar.get(Calendar.DAY_OF_MONTH);

        fc.setIdCaja(idCaja);
        fc.setIdVendedor(Login.idVendedor);
        fc.setFecha(anno + "-" + mes + "-" + dia);
        if (fcdao.cajaAbierta(fc)) {
            menuGenerarVenta.setEnabled(true);
        } else {
            menuGenerarVenta.setEnabled(false);
        }
    }

    void privilegio(String tipo) {
        if (tipo == "admin") {
            //jMenu2.setEnabled(false);
        } else {
            jMenu3.setEnabled(false);
            jMenu4.setEnabled(false);
            jMenu1.setEnabled(false);
            jMenu5.setEnabled(false);
        }
    }

    private void menuGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerarVentaActionPerformed
        VentasForm v = new VentasForm();
        centrarVentana(v);
    }//GEN-LAST:event_menuGenerarVentaActionPerformed

    void centrarVentana(JInternalFrame frame) {
        ventanaPrincipal.add(frame);
        Dimension dimension = ventanaPrincipal.getSize();
        Dimension sizeFrame = frame.getSize();
        frame.setVisible(true);
        frame.setLocation((dimension.width - sizeFrame.height) / 2, (dimension.height - sizeFrame.width) / 2);
    }

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        CategoriaForm c = new CategoriaForm();
        centrarVentana(c);
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendedorActionPerformed
        VendedorForm v = new VendedorForm();
        centrarVentana(v);
    }//GEN-LAST:event_menuVendedorActionPerformed

    private void menuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductoActionPerformed
        ProductoForm p = new ProductoForm();
        centrarVentana(p);
    }//GEN-LAST:event_menuProductoActionPerformed

    private void menuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarActionPerformed
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuCerrarActionPerformed

    private void menuRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRankingActionPerformed
        RankingForm r = new RankingForm();
        centrarVentana(r);
    }//GEN-LAST:event_menuRankingActionPerformed

    private void menuIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresosActionPerformed
        IngresosForm i = new IngresosForm();
        centrarVentana(i);
    }//GEN-LAST:event_menuIngresosActionPerformed

    private void menuActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarActionPerformed
        ActualizarAdminForm a = new ActualizarAdminForm();
        centrarVentana(a);
    }//GEN-LAST:event_menuActualizarActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        ClienteForm c = new ClienteForm();
        centrarVentana(c);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProveedorActionPerformed
        ProveedorForm p = new ProveedorForm();
        centrarVentana(p);
    }//GEN-LAST:event_menuProveedorActionPerformed

    private void menuGenerarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerarCompraActionPerformed
        ComprasForm c = new ComprasForm();
        centrarVentana(c);
    }//GEN-LAST:event_menuGenerarCompraActionPerformed

    private void menuEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEgresosActionPerformed
        EgresosForm e = new EgresosForm();
        centrarVentana(e);
    }//GEN-LAST:event_menuEgresosActionPerformed

    private void menuCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCajaActionPerformed
        CajaForm c = new CajaForm();
        centrarVentana(c);
    }//GEN-LAST:event_menuCajaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menuActualizar;
    private javax.swing.JMenuItem menuCaja;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuCerrar;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuEgresos;
    private javax.swing.JMenuItem menuGenerarCompra;
    private javax.swing.JMenuItem menuGenerarVenta;
    private javax.swing.JMenuItem menuIngresos;
    private javax.swing.JMenuItem menuProducto;
    private javax.swing.JMenuItem menuProveedor;
    private javax.swing.JMenuItem menuRanking;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuVendedor;
    private javax.swing.JDesktopPane ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
